services:
  paraunit.configuration.paraunit:
    class: Paraunit\Configuration\Paraunit

  paraunit.configuration.phpunit_bin_file:
    class: Paraunit\Configuration\PHPUnitBinFile

  paraunit.configuration.phpdbg_bin_file:
    class: Paraunit\Configuration\PHPDbgBinFile

  paraunit.configuration.json_log_filename:
    class: Paraunit\Configuration\JSONLogFilename
    arguments:
      - "@paraunit.file.temp_directory"
