services:
  paraunit.coverage.coverage_fetcher:
    class: Paraunit\Coverage\CoverageFetcher
    arguments:
      - "@paraunit.configuration.temp_filename_factory"

  paraunit.coverage.coverage_merger:
    class: Paraunit\Coverage\CoverageMerger
    arguments:
      - "@paraunit.coverage.coverage_fetcher"
    tags:
      - { name: kernel.event_listener, event: process_event.process_terminated, method: onProcessTerminated }

  paraunit.coverage.coverage_result:
    class: Paraunit\Coverage\CoverageResult
    arguments:
      - "@paraunit.coverage.coverage_merger"
      - "@paraunit.coverage.coverage_output_paths"
      - "@paraunit.proxy.coverage.clover_result"
      - "@paraunit.proxy.coverage.xml_result"
      - "@paraunit.proxy.coverage.html_result"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: generateResults }

  paraunit.coverage.coverage_output_paths:
    class: Paraunit\Coverage\CoverageOutputPaths
    arguments:
      - "@paraunit.configuration.clover_file_path"
      - "@paraunit.configuration.xml_path"
      - "@paraunit.configuration.html_path"
